version: '3.8'

# Development Docker Compose with correct build args
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # CRITICAL: Set at BUILD TIME
        # Use /api for production (nginx proxy handles routing)
        # Use http://backend:port/api for direct backend access (dev only)
        REACT_APP_API_URL: /api
        NODE_ENV: development
    environment:
      # These are for nginx, not React
      BACKEND_HOST: backend-dev
      BACKEND_PORT: 5050
      FRONTEND_PORT: 3000
    ports:
      - "3000:80"
    networks:
      - figure-collector

networks:
  figure-collector:
    external: true