version: '3.8'

# Development Docker Compose with correct build args
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # CRITICAL: Set at BUILD TIME
        # Always use /api when nginx proxy is present (both dev and prod)
        # Only use http://backend:port/api for local development without nginx
        REACT_APP_API_URL: /api
        NODE_ENV: development
    environment:
      # These are for nginx, not React
      BACKEND_HOST: backend-dev
      BACKEND_PORT: 5050
      FRONTEND_PORT: 3000
    ports:
      - "3000:80"
    networks:
      - figure-collector

networks:
  figure-collector:
    external: true